# sfm algorithm configure
social_force:
  animation_factor: 5.1
  # only handle pedestrians within `people_distance`
  people_distance: 6.0
  # weights of social force model
  goal_weight: 2.0
  obstacle_weight: 20.0
  social_weight: 15
  group_gaze_weight: 3.0
  group_coh_weight: 2.0
  group_rep_weight: 1.0

# pedestrians setting
pedestrians:
  update_rate: 5
  ped_property:
    - name: human_1
      scale: 0.6
      pose: 0.5 0 1 0 0 0
      velocity: 0.6
      radius: 0.25
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 0.5 0 1 0 0 0
        goal_point_2: -0.5 -1 1 0 0 0
    # - name: human_2
    #   scale: 0.2
    #   pose: 6 0 1 0 0 0
    #   velocity: 1.2
    #   radius: 0.4
    #   cycle: true
    #   ignore:
    #     model_1: ground_plane
    #     model_2: turtlebot3_waffle
    #   trajectory:
    #     goal_point_1: 6 0 1 0 0 0
    #     goal_point_2: -4 0 1 0 0 0
    - name: moving_box
      type: box
      pose: -3 -4 0.25 0 0 0
      velocity: 0.8
      radius: 0.4
      size: 0.4
      color: 1 0 0 1
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: -3 -4 0.25 0 0 0
        goal_point_2: 5 -4 0.25 0 0 0
