

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAMES ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAMES ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findosqp.cmake")
# Global approach
set(osqp_FOUND 1)
set(osqp_VERSION "0.6.3")

find_package_handle_standard_args(osqp REQUIRED_VARS
                                  osqp_VERSION VERSION_VAR osqp_VERSION)
mark_as_advanced(osqp_FOUND osqp_VERSION)


set(osqp_INCLUDE_DIRS "/home/lcy/.conan/data/osqp/0.6.3/_/_/package/69f8db40e683434496cb58e4d4030f8979815e1a/include")
set(osqp_INCLUDE_DIR "/home/lcy/.conan/data/osqp/0.6.3/_/_/package/69f8db40e683434496cb58e4d4030f8979815e1a/include")
set(osqp_INCLUDES "/home/lcy/.conan/data/osqp/0.6.3/_/_/package/69f8db40e683434496cb58e4d4030f8979815e1a/include")
set(osqp_RES_DIRS )
set(osqp_DEFINITIONS )
set(osqp_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(osqp_COMPILE_DEFINITIONS )
set(osqp_COMPILE_OPTIONS_LIST "" "")
set(osqp_COMPILE_OPTIONS_C "")
set(osqp_COMPILE_OPTIONS_CXX "")
set(osqp_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(osqp_LIBRARIES "") # Will be filled later
set(osqp_LIBS "") # Same as osqp_LIBRARIES
set(osqp_SYSTEM_LIBS m rt dl)
set(osqp_FRAMEWORK_DIRS )
set(osqp_FRAMEWORKS )
set(osqp_FRAMEWORKS_FOUND "") # Will be filled later
set(osqp_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(osqp_FRAMEWORKS_FOUND "${osqp_FRAMEWORKS}" "${osqp_FRAMEWORK_DIRS}")

mark_as_advanced(osqp_INCLUDE_DIRS
                 osqp_INCLUDE_DIR
                 osqp_INCLUDES
                 osqp_DEFINITIONS
                 osqp_LINKER_FLAGS_LIST
                 osqp_COMPILE_DEFINITIONS
                 osqp_COMPILE_OPTIONS_LIST
                 osqp_LIBRARIES
                 osqp_LIBS
                 osqp_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to osqp_LIBS and osqp_LIBRARY_LIST
set(osqp_LIBRARY_LIST osqp)
set(osqp_LIB_DIRS "/home/lcy/.conan/data/osqp/0.6.3/_/_/package/69f8db40e683434496cb58e4d4030f8979815e1a/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_osqp_DEPENDENCIES "${osqp_FRAMEWORKS_FOUND} ${osqp_SYSTEM_LIBS} ")

conan_package_library_targets("${osqp_LIBRARY_LIST}"  # libraries
                              "${osqp_LIB_DIRS}"      # package_libdir
                              "${_osqp_DEPENDENCIES}"  # deps
                              osqp_LIBRARIES            # out_libraries
                              osqp_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "osqp")                                      # package_name

set(osqp_LIBS ${osqp_LIBRARIES})

foreach(_FRAMEWORK ${osqp_FRAMEWORKS_FOUND})
    list(APPEND osqp_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND osqp_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${osqp_SYSTEM_LIBS})
    list(APPEND osqp_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND osqp_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(osqp_LIBRARIES_TARGETS "${osqp_LIBRARIES_TARGETS};")
set(osqp_LIBRARIES "${osqp_LIBRARIES};")

set(CMAKE_MODULE_PATH "/home/lcy/.conan/data/osqp/0.6.3/_/_/package/69f8db40e683434496cb58e4d4030f8979815e1a/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/lcy/.conan/data/osqp/0.6.3/_/_/package/69f8db40e683434496cb58e4d4030f8979815e1a/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET osqp::osqp)
        add_library(osqp::osqp INTERFACE IMPORTED)
        if(osqp_INCLUDE_DIRS)
            set_target_properties(osqp::osqp PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${osqp_INCLUDE_DIRS}")
        endif()
        set_property(TARGET osqp::osqp PROPERTY INTERFACE_LINK_LIBRARIES
                     "${osqp_LIBRARIES_TARGETS};${osqp_LINKER_FLAGS_LIST}")
        set_property(TARGET osqp::osqp PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${osqp_COMPILE_DEFINITIONS})
        set_property(TARGET osqp::osqp PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${osqp_COMPILE_OPTIONS_LIST}")
        
    endif()
endif()

foreach(_BUILD_MODULE_PATH ${osqp_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
