########## MACROS ###########################################################################
#############################################################################################

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAMES ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAMES ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


########### FOUND PACKAGE ###################################################################
#############################################################################################

include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated FindCeres.cmake")
set(Ceres_FOUND 1)
set(Ceres_VERSION "1.14.0")

find_package_handle_standard_args(Ceres REQUIRED_VARS
                                  Ceres_VERSION VERSION_VAR Ceres_VERSION)
mark_as_advanced(Ceres_FOUND Ceres_VERSION)

set(Ceres_COMPONENTS Ceres::ceres)

if(Ceres_FIND_COMPONENTS)
    foreach(_FIND_COMPONENT ${Ceres_FIND_COMPONENTS})
        list(FIND Ceres_COMPONENTS "Ceres::${_FIND_COMPONENT}" _index)
        if(${_index} EQUAL -1)
            conan_message(FATAL_ERROR "Conan: Component '${_FIND_COMPONENT}' NOT found in package 'Ceres'")
        else()
            conan_message(STATUS "Conan: Component '${_FIND_COMPONENT}' found in package 'Ceres'")
        endif()
    endforeach()
endif()

########### VARIABLES #######################################################################
#############################################################################################


set(Ceres_INCLUDE_DIRS "/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include"
			"/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include/ceres")
set(Ceres_INCLUDE_DIR "/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include;/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include/ceres")
set(Ceres_INCLUDES "/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include"
			"/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include/ceres")
set(Ceres_RES_DIRS )
set(Ceres_DEFINITIONS )
set(Ceres_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(Ceres_COMPILE_DEFINITIONS )
set(Ceres_COMPILE_OPTIONS_LIST "" "")
set(Ceres_COMPILE_OPTIONS_C "")
set(Ceres_COMPILE_OPTIONS_CXX "")
set(Ceres_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(Ceres_LIBRARIES "") # Will be filled later
set(Ceres_LIBS "") # Same as Ceres_LIBRARIES
set(Ceres_SYSTEM_LIBS m)
set(Ceres_FRAMEWORK_DIRS )
set(Ceres_FRAMEWORKS )
set(Ceres_FRAMEWORKS_FOUND "") # Will be filled later
set(Ceres_BUILD_MODULES_PATHS "/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/lib/cmake/conan-official-ceres-solver-variables.cmake")

conan_find_apple_frameworks(Ceres_FRAMEWORKS_FOUND "${Ceres_FRAMEWORKS}" "${Ceres_FRAMEWORK_DIRS}")

mark_as_advanced(Ceres_INCLUDE_DIRS
                 Ceres_INCLUDE_DIR
                 Ceres_INCLUDES
                 Ceres_DEFINITIONS
                 Ceres_LINKER_FLAGS_LIST
                 Ceres_COMPILE_DEFINITIONS
                 Ceres_COMPILE_OPTIONS_LIST
                 Ceres_LIBRARIES
                 Ceres_LIBS
                 Ceres_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to Ceres_LIBS and Ceres_LIBRARY_LIST
set(Ceres_LIBRARY_LIST ceres)
set(Ceres_LIB_DIRS "/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_Ceres_DEPENDENCIES "${Ceres_FRAMEWORKS_FOUND} ${Ceres_SYSTEM_LIBS} Eigen3::Eigen3;glog::glog")

conan_package_library_targets("${Ceres_LIBRARY_LIST}"  # libraries
                              "${Ceres_LIB_DIRS}"      # package_libdir
                              "${_Ceres_DEPENDENCIES}"  # deps
                              Ceres_LIBRARIES            # out_libraries
                              Ceres_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "Ceres")                                      # package_name

set(Ceres_LIBS ${Ceres_LIBRARIES})

foreach(_FRAMEWORK ${Ceres_FRAMEWORKS_FOUND})
    list(APPEND Ceres_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND Ceres_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${Ceres_SYSTEM_LIBS})
    list(APPEND Ceres_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND Ceres_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(Ceres_LIBRARIES_TARGETS "${Ceres_LIBRARIES_TARGETS};Eigen3::Eigen3;glog::glog")
set(Ceres_LIBRARIES "${Ceres_LIBRARIES};Eigen3::Eigen3;glog::glog")

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})


########### COMPONENT ceres VARIABLES #############################################

set(Ceres_ceres_INCLUDE_DIRS "/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include"
			"/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include/ceres")
set(Ceres_ceres_INCLUDE_DIR "/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include;/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include/ceres")
set(Ceres_ceres_INCLUDES "/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include"
			"/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/include/ceres")
set(Ceres_ceres_LIB_DIRS "/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/lib")
set(Ceres_ceres_RES_DIRS )
set(Ceres_ceres_DEFINITIONS )
set(Ceres_ceres_COMPILE_DEFINITIONS )
set(Ceres_ceres_COMPILE_OPTIONS_C "")
set(Ceres_ceres_COMPILE_OPTIONS_CXX "")
set(Ceres_ceres_LIBS ceres)
set(Ceres_ceres_SYSTEM_LIBS m)
set(Ceres_ceres_FRAMEWORK_DIRS )
set(Ceres_ceres_FRAMEWORKS )
set(Ceres_ceres_BUILD_MODULES_PATHS "/home/lcy/.conan/data/ceres-solver/1.14.0/_/_/package/0f9698a1b33a9f1c0a2424ab168611b7b74df414/lib/cmake/conan-official-ceres-solver-variables.cmake")
set(Ceres_ceres_DEPENDENCIES Eigen3::Eigen3 glog::glog)
set(Ceres_ceres_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)


########## FIND PACKAGE DEPENDENCY ##########################################################
#############################################################################################

include(CMakeFindDependencyMacro)

if(NOT Eigen3_FOUND)
    find_dependency(Eigen3 REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency Eigen3 already found")
endif()

if(NOT glog_FOUND)
    find_dependency(glog REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency glog already found")
endif()


########## FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #######################################
#############################################################################################

########## COMPONENT ceres FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(Ceres_ceres_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(Ceres_ceres_FRAMEWORKS_FOUND "${Ceres_ceres_FRAMEWORKS}" "${Ceres_ceres_FRAMEWORK_DIRS}")

set(Ceres_ceres_LIB_TARGETS "")
set(Ceres_ceres_NOT_USED "")
set(Ceres_ceres_LIBS_FRAMEWORKS_DEPS ${Ceres_ceres_FRAMEWORKS_FOUND} ${Ceres_ceres_SYSTEM_LIBS} ${Ceres_ceres_DEPENDENCIES})
conan_package_library_targets("${Ceres_ceres_LIBS}"
                              "${Ceres_ceres_LIB_DIRS}"
                              "${Ceres_ceres_LIBS_FRAMEWORKS_DEPS}"
                              Ceres_ceres_NOT_USED
                              Ceres_ceres_LIB_TARGETS
                              ""
                              "Ceres_ceres")

set(Ceres_ceres_LINK_LIBS ${Ceres_ceres_LIB_TARGETS} ${Ceres_ceres_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH})


########## TARGETS ##########################################################################
#############################################################################################

########## COMPONENT ceres TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET Ceres::ceres)
        add_library(Ceres::ceres INTERFACE IMPORTED)
        set_target_properties(Ceres::ceres PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${Ceres_ceres_INCLUDE_DIRS}")
        set_target_properties(Ceres::ceres PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${Ceres_ceres_LIB_DIRS}")
        set_target_properties(Ceres::ceres PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${Ceres_ceres_LINK_LIBS};${Ceres_ceres_LINKER_FLAGS_LIST}")
        set_target_properties(Ceres::ceres PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${Ceres_ceres_COMPILE_DEFINITIONS}")
        set_target_properties(Ceres::ceres PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${Ceres_ceres_COMPILE_OPTIONS_C};${Ceres_ceres_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## GLOBAL TARGET ####################################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    if(NOT TARGET Ceres::Ceres)
        add_library(Ceres::Ceres INTERFACE IMPORTED)
    endif()
    set_property(TARGET Ceres::Ceres APPEND PROPERTY
                 INTERFACE_LINK_LIBRARIES "${Ceres_COMPONENTS}")
endif()

########## BUILD MODULES ####################################################################
#############################################################################################
########## COMPONENT ceres BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${Ceres_ceres_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
